name: Build Full Ticketing App

on:
  workflow_dispatch:   # <-- manual trigger only

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ------------------------------
      # Backend Build + Push
      # ------------------------------
      - name: Build Backend Image
        run: |
          docker build \
            -t mohitrajguru/ticketing-backend:latest \
            ./Ticketing-Backend

      - name: Push Backend Image
        run: |
          docker push mohitrajguru/ticketing-backend:latest

      # ------------------------------
      # Frontend Build + Push
      # ------------------------------
      - name: Build Frontend Image
        run: |
          docker build \
            -t mohitrajguru/ticketing-frontend:latest \
            ./Ticketing-Frontend

      - name: Push Frontend Image
        run: |
          docker push mohitrajguru/ticketing-frontend:latest
